services:
  db:
    image: mariadb:11.7
    environment:
      MARIADB_USER: mariadb
      MARIADB_PASSWORD: supersecret
      MARIADB_DATABASE: mariadb
      MARIADB_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  service:
    build: website
    environment:
      FLAG: flag{REDACTED}
      DB_HOST: db
      DB_NAME: mariadb
      DB_USER: mariadb
      DB_PASSWORD: supersecret
      DOMAIN: http://service:3000
      HEADLESS_HOST: headless:5000
      HEADLESS_AUTH: supersecret
      CHECKER_TOKEN: supersecret
    ports:
      - 3000:3000

  headless:
    image: cybersecnatlab/challenge-headless:latest-manager
    restart: unless-stopped
    environment:
      AUTH_TOKEN: supersecret
      RABBITMQ_HOST: headless-rabbitmq
      RABBITMQ_QUEUE: headless-jobs
    depends_on:
      - headless-rabbitmq

  headless-rabbitmq:
    image: rabbitmq:3.11
    restart: unless-stopped

  headless-worker:
    image: cybersecnatlab/challenge-headless:latest-worker
    restart: unless-stopped
    environment:
      RABBITMQ_HOST: headless-rabbitmq
      RABBITMQ_QUEUE: headless-jobs
    deploy:
      replicas: 1
    depends_on:
      - headless-rabbitmq