/* This file was generated by the Hex-Rays decompiler version 9.3.0.260213.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
void sub_1020();
void sub_1030();
void sub_1040();
void sub_1050();
void sub_1060();
void sub_1070();
void sub_1080();
void sub_1090();
void sub_10A0();
void sub_10B0();
void sub_10C0();
void sub_10D0();
void sub_10E0();
void sub_10F0();
void sub_1100();
// int _cxa_finalize(void *);
// void free(void *ptr);
// int puts(const char *s);
// int fclose(FILE *stream);
// int printf(const char *format, ...);
// size_t strcspn(const char *s, const char *reject);
// int fprintf(FILE *stream, const char *format, ...);
// int feof(FILE *stream);
// __int64 __fastcall gets(_QWORD); weak
// int setvbuf(FILE *stream, char *buf, int modes, size_t n);
// FILE *fopen(const char *filename, const char *modes);
// __int64 __isoc99_scanf(const char *, ...); weak
// __ssize_t getline(char **lineptr, size_t *n, FILE *stream);
// __int64 __fastcall getrandom(_QWORD, _QWORD, _QWORD); weak
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)());
FILE **deregister_tm_clones();
__int64 register_tm_clones(void); // weak
FILE **_do_global_dtors_aux();
__int64 frame_dummy(); // weak
__int64 __fastcall gameInit(_QWORD); // weak
__int64 __fastcall gameWelcome(_QWORD); // weak
__int64 __fastcall gamePlay(_QWORD); // weak
int gameSaveScore();
unsigned __int64 gameShowScores();
int __fastcall main(int argc, const char **argv, const char **envp);
void term_proc();
// int _libc_start_main(int (*main)(int, char **, char **), int argc, char **ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)(), void *stack_end);
// int __cxa_finalize(void *);
// __int64 ITM_deregisterTMCloneTable(void); weak
// __int64 _gmon_start__(void); weak
// __int64 ITM_registerTMCloneTable(void); weak

//-------------------------------------------------------------------------
// Data declarations

const char byte_2188 = '\0'; // idb
void *_dso_handle = &_dso_handle; // idb
FILE *stdout; // idb
FILE *stdin; // idb
char completed_0; // weak
char gamedata[20]; // weak
int dword_4044; // weak
int dword_4048; // weak


//----- (0000000000001000) ----------------------------------------------------
// Alternative name is '_init'
__int64 (**init_proc())(void)
{
  __int64 (**result)(void); // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    return (__int64 (**)(void))_gmon_start__();
  return result;
}
// 40E0: using guessed type __int64 _gmon_start__(void);

//----- (0000000000001020) ----------------------------------------------------
void sub_1020()
{
  JUMPOUT(0);
}
// 1026: control flows out of bounds to 0

//----- (0000000000001030) ----------------------------------------------------
void sub_1030()
{
  sub_1020();
}

//----- (0000000000001040) ----------------------------------------------------
void sub_1040()
{
  sub_1020();
}

//----- (0000000000001050) ----------------------------------------------------
void sub_1050()
{
  sub_1020();
}

//----- (0000000000001060) ----------------------------------------------------
void sub_1060()
{
  sub_1020();
}

//----- (0000000000001070) ----------------------------------------------------
void sub_1070()
{
  sub_1020();
}

//----- (0000000000001080) ----------------------------------------------------
void sub_1080()
{
  sub_1020();
}

//----- (0000000000001090) ----------------------------------------------------
void sub_1090()
{
  sub_1020();
}

//----- (00000000000010A0) ----------------------------------------------------
void sub_10A0()
{
  sub_1020();
}

//----- (00000000000010B0) ----------------------------------------------------
void sub_10B0()
{
  sub_1020();
}

//----- (00000000000010C0) ----------------------------------------------------
void sub_10C0()
{
  sub_1020();
}

//----- (00000000000010D0) ----------------------------------------------------
void sub_10D0()
{
  sub_1020();
}

//----- (00000000000010E0) ----------------------------------------------------
void sub_10E0()
{
  sub_1020();
}

//----- (00000000000010F0) ----------------------------------------------------
void sub_10F0()
{
  sub_1020();
}

//----- (0000000000001100) ----------------------------------------------------
void sub_1100()
{
  sub_1020();
}

//----- (0000000000001200) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)())
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  _libc_start_main((int (*)(int, char **, char **))main, v4, &retaddr, nullptr, nullptr, a3, &v5);
  __halt();
}
// 120A: positive sp value 8 has been found
// 1211: variable 'v3' is possibly undefined

//----- (0000000000001230) ----------------------------------------------------
FILE **deregister_tm_clones()
{
  return &stdout;
}
// 40D8: using guessed type __int64 ITM_deregisterTMCloneTable(void);

//----- (0000000000001260) ----------------------------------------------------
__int64 register_tm_clones()
{
  return 0;
}
// 1260: using guessed type __int64 register_tm_clones();
// 40E8: using guessed type __int64 ITM_registerTMCloneTable(void);

//----- (00000000000012A0) ----------------------------------------------------
FILE **_do_global_dtors_aux()
{
  FILE **result; // rax

  if ( !completed_0 )
  {
    if ( &__cxa_finalize )
      _cxa_finalize(_dso_handle);
    result = deregister_tm_clones();
    completed_0 = 1;
  }
  return result;
}
// 4028: using guessed type char completed_0;

//----- (00000000000012E0) ----------------------------------------------------
__int64 frame_dummy()
{
  return register_tm_clones();
}
// 1260: using guessed type __int64 register_tm_clones(void);
// 12E0: using guessed type __int64 frame_dummy();

//----- (00000000000012E9) ----------------------------------------------------
__int64 gameInit()
{
  dword_4044 = 5;
  return getrandom(&dword_4048, 4, 0);
}
// 11F0: using guessed type __int64 __fastcall getrandom(_QWORD, _QWORD, _QWORD);
// 12E9: using guessed type __int64 gameInit();
// 4044: using guessed type int dword_4044;
// 4048: using guessed type int dword_4048;

//----- (0000000000001317) ----------------------------------------------------
__int64 gameWelcome()
{
  puts("Welcome to GuessTheNumber!");
  puts("Please enter your name so that you can be added to the high scores:");
  return gets(&gamedata);
}
// 11A0: using guessed type __int64 __fastcall gets(_QWORD);
// 1317: using guessed type __int64 gameWelcome();

//----- (0000000000001354) ----------------------------------------------------
__int64 gamePlay()
{
  int v1; // [rsp+Ch] [rbp-24h] BYREF
  char *lineptr; // [rsp+10h] [rbp-20h] BYREF
  size_t n; // [rsp+18h] [rbp-18h] BYREF
  FILE *stream; // [rsp+20h] [rbp-10h]
  unsigned __int64 v5; // [rsp+28h] [rbp-8h]

  v5 = __readfsqword(0x28u);
  puts("What number am I thinking about? Try to guess it!");
  while ( dword_4044 > 0 )
  {
    --dword_4044;
    __isoc99_scanf("%d", &v1);
    if ( dword_4048 == v1 )
    {
      printf("Well done %s! You earned a place in the high-scores and a little treat!\n", gamedata);
      stream = fopen("flag", "r");
      lineptr = nullptr;
      n = 0;
      getline(&lineptr, &n, stream);
      fclose(stream);
      printf("Your treat: %s", lineptr);
      free(lineptr);
      return 1;
    }
    if ( dword_4048 >= v1 )
      puts("Try higher ;)");
    else
      puts("Try lower ;)");
  }
  puts("No luck! :(");
  printf("The number was %d\n", dword_4048);
  puts("Try again, eventually you will succed!");
  return 0;
}
// 11D0: using guessed type __int64 __isoc99_scanf(const char *, ...);
// 1354: using guessed type __int64 gamePlay();
// 4044: using guessed type int dword_4044;
// 4048: using guessed type int dword_4048;

//----- (00000000000014EA) ----------------------------------------------------
int gameSaveScore()
{
  FILE *v0; // rax
  FILE *stream; // [rsp+8h] [rbp-8h]

  v0 = fopen("/tmp/scores.txt", "a");
  stream = v0;
  if ( v0 )
  {
    fprintf(v0, "%s,%d\n", gamedata, 5 - dword_4044);
    LODWORD(v0) = fclose(stream);
  }
  return (int)v0;
}
// 4044: using guessed type int dword_4044;

//----- (0000000000001559) ----------------------------------------------------
unsigned __int64 gameShowScores()
{
  char *lineptr; // [rsp+8h] [rbp-28h] BYREF
  size_t n; // [rsp+10h] [rbp-20h] BYREF
  FILE *stream; // [rsp+18h] [rbp-18h]
  size_t v4; // [rsp+20h] [rbp-10h]
  unsigned __int64 v5; // [rsp+28h] [rbp-8h]

  v5 = __readfsqword(0x28u);
  puts(&byte_2188);
  puts("HIGH SCORES");
  stream = fopen("/tmp/scores.txt", "r");
  if ( stream )
  {
    lineptr = nullptr;
    n = 0;
    puts("Name\tTries");
    while ( !feof(stream) )
    {
      getline(&lineptr, &n, stream);
      v4 = strcspn(lineptr, ",");
      if ( lineptr[v4] )
      {
        lineptr[v4] = 0;
        printf("%s\t%s", lineptr, &lineptr[v4 + 1]);
      }
      free(lineptr);
      lineptr = nullptr;
      n = 0;
    }
    fclose(stream);
  }
  else
  {
    puts("No high scores yet :(");
  }
  return v5 - __readfsqword(0x28u);
}

//----- (00000000000016BB) ----------------------------------------------------
int __fastcall main(int argc, const char **argv, const char **envp)
{
  FILE *v3; // rdi

  setvbuf(stdout, nullptr, 2, 0);
  v3 = stdin;
  setvbuf(stdin, nullptr, 2, 0);
  gameInit(v3);
  gameWelcome(v3);
  if ( (unsigned int)gamePlay(v3) )
    gameSaveScore();
  gameShowScores();
  return 0;
}
// 12E9: using guessed type __int64 __fastcall gameInit(_QWORD);
// 1317: using guessed type __int64 __fastcall gameWelcome(_QWORD);
// 1354: using guessed type __int64 __fastcall gamePlay(_QWORD);

//----- (0000000000001748) ----------------------------------------------------
// Alternative name is '_fini'
void term_proc()
{
  ;
}

// nfuncs=62 queued=28 decompiled=28 lumina nreq=0 worse=0 better=0
// ALL OK, 28 function(s) have been successfully decompiled
